services:
  web:
    build: . 
    container_name: my_flask_app
    ports:
      - "5000:5000" 
    environment:
      DATABASE_URL: postgresql://postgres:123@db:5432/book
      FLASK_APP: app.py 
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16
    container_name: my_postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: book
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432" 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d book"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  tests:
    image: postman/newman
    working_dir: /etc/newman
    volumes:
      - ./API_TEST.postman_collection.json:/etc/newman/API_TEST.postman_collection.json
      - ./New_Environment.postman_environment.json:/etc/newman/New_Environment.postman_environment.json
      - ./test-results:/etc/newman/results 
    
    command: >
      run API_TEST.postman_collection.json
      -e New_Environment.postman_environment.json
      -r cli,htmlextra
      --reporter-htmlextra-export /etc/newman/results/report.html
      
    depends_on:
      - web

volumes:
  postgres_data: